name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-20.04
    env:
      POETRY_CACHE_DIR: "${{ github.workspace }}/.cache/pypoetry"
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        key: poetry-${{ runner.os }}-py${{ matrix.python }}-${{ hashFiles('poetry.lock') }}
        path: |
          .cache/pypoetry
    - uses: actions/setup-python@v2
      with:
        python-version: '3.6'
    - uses: Gr1N/setup-poetry@v7
    - name: Setup virtualenv
      run: poetry install
    - name: Lint
      run: make -k -j4 lint
  test:
    needs: lint
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-20.04', "windows-2019", "macos-10.15"]
        python: ['3.6', '3.7', '3.8', '3.9', '3.10']
    runs-on: ${{ matrix.os }}
    env:
      POETRY_CACHE_DIR: "${{ github.workspace }}/.cache/pypoetry"
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        key: poetry-${{ runner.os }}-py${{ matrix.python }}-${{ hashFiles('poetry.lock') }}
        path: |
          .cache/pypoetry
    - uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}
    - uses: Gr1N/setup-poetry@v7
    - name: Setup virtualenv
      run: poetry install
    - name: Test
      run: make test
